apiVersion: 1

contactPoints:
  - orgId: 1
    name: homelab-email
    receivers:
      - uid: homelab-email-receiver
        type: email
        settings:
          addresses: ${GF_ALERT_EMAIL}
          singleEmail: false
